### ISSUE TITLE
pod install generates  Generated duplicate UUIDs warning

### ISSUE THREAD

**Issue by efstathiosntonas** [hhunaid/react-native-image-crop-tools#13]
On `pod install` it throws the following warning: 

`[!] [Xcodeproj] Generated duplicate UUIDs`

a temp fix is to add this in `Podfile`

```
platform :ios, '10.0'
install! 'cocoapods', :deterministic_uuids => false
```

more info: https://github.com/CocoaPods/CocoaPods/issues/4370

**Comment by hhunaid** [comment]
Thanks for reporting. I will take a look when I get a chance

**Comment by hhunaid** [comment]
Fixed in latest
