### ISSUE TITLE
saveImage() function causes java exception

### ISSUE THREAD

**Issue by ozkanonur** [hhunaid/react-native-image-crop-tools#2]
Hey there, whatever value(between 1 and 100) I give the saveImage() function, I get the java exception 'java.lang.Double cannot be cast to java.lang.Boolean' but in [here](https://github.com/hhunaid/react-native-image-crop-tools/blob/master/android/src/main/java/com/parsempo/ImageCropTools/ImageCropViewManager.kt#L77) when I replace the line with this `val quality = 100` problem gets solved. I dont know much about kotlin so I decided to let you know that problem.

**Comment by hhunaid** [comment]
There was a breaking change in the most recent version where `saveImage` now takes 2 parameters. 1st is a boolean which tells if you want to keep the transparency i.e. generate a png or a jpg. 2nd argument takes the quality. I have updated the readme to reflect this

**Comment by ozkanonur** [comment]
Ah okay then, I didnt see it sorry. Thanks for quick response.
