### ISSUE TITLE
Fixed Crop View

### ISSUE THREAD

**Issue by Abdullah1428** [hhunaid/react-native-image-crop-tools#23]
Hello, First of all, great work with this package.

I wanted to know that can we make the crop view fixed for the image and the user can just drag the image?
In the end, only that part of the image will be cropped which is viewable inside the crop rectangle.

Thank You.

**Comment by hhunaid** [comment]
You can fix the aspect ratio but the user can still resize it.

**Comment by Abdullah1428** [comment]
Okay so there is no way to prevent user from resizing it?

Actually i want to crop the picture for a specific aspect ratio.

**Comment by hhunaid** [comment]
Aspect ratio can be fixed. But the user can resize while being in that aspect ratio. So if you set the ratio to be 16:9 they can have any size that confirms to 16:9.

**Comment by Abdullah1428** [comment]
Okay got it.
Thank you for the reply.
