### ISSUE TITLE
onImageCrop not triggering.

### ISSUE THREAD

**Issue by askmakdag** [hhunaid/react-native-image-crop-tools#31]
component usage: 
**{uri !== undefined && (
            <CropView
              sourceUrl={uri}
              style={styles.cropView}
              ref={cropViewRef}
              onImageCrop={(res) => console.log('hello...')}
              keepAspectRatio
              aspectRatio={{width: 1, height: 1}}
            />
          )}**

triggering func:     
**cropViewRef.current.saveImage(90);**

related podFile settings added ...
Nothing happening on **IOS rnV-0.63.4**

**Comment by yashimaskara** [comment]
anyone got the answer?
