### ISSUE TITLE
[Android] 0.64 crashes on UIManager

### ISSUE THREAD

**Issue by efstathiosntonas** [hhunaid/react-native-image-crop-tools#32]
It seems by trying to move the crop box on Android with `react-native 0.64` results in crash, this crash is related with https://github.com/facebook/react-native/issues/31245, only way to fix is to downgrade to 0.63.4

**Comment by efstathiosntonas** [comment]
This should be fixed on rn 0.64.2, not tested it yet though.

**Comment by wijayantoap** [comment]
Tested on RN 0.64.2 and it is fixed

**Comment by hhunaid** [comment]
Closing for now
