### ISSUE TITLE
requireNativeComponent: "CropView" was not found in the UIManager

### ISSUE THREAD

**Issue by MikhailVasiliev** [hhunaid/react-native-image-crop-tools#4]
I got this error.

What I've done:
* npm i react-native-image-crop-tools (also tried via yarn)
* pod install

Versions: 
* react-native - 0.61.5
* react - 16.9.0
* react-native-image-crop-tools - 1.3.4

![Simulator Screen Shot - iPhone 8 - 2020-01-27 at 19 27 05](https://user-images.githubusercontent.com/24992980/73218065-d76b7b80-4161-11ea-8c9b-41d4494e6018.png)

**Comment by MikhailVasiliev** [comment]
@hhunaid

**Comment by hhunaid** [comment]
Add `pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'` in your podfile below the line `use_native_modules!`. And then run pod install again.

For some reason, auto-linking doesn't pick up this module. I'm looking into it.

**Comment by MikhailVasiliev** [comment]
@hhunaid , cool, thanks, it works now)

**Comment by JimTeva** [comment]
Thanks @hhunaid for this great library, you made my day!

**Comment by Nacho-source** [comment]
@hhunaid I already have that line in my Podfile but this error keeps Showing up
Of course I've also tried removing Podfile.lock -> npm install -> pod install but nothing changes

Any ideas?

Versions: 

- react-native - 0.62.3
- react - 16.11.0

I've tried with 1.3.0 and 1.5.0 Versions of `react-native-image-crop-tools `

**Comment by madanmurari007** [comment]
Same issue

**Comment by thangpq-ahiho** [comment]
have anyone solved this problem?

**Comment by jaysoniNucleus** [comment]
Getting same issue for android device,

Invariant Violation: requireNativeComponent: "CropView" was not found in the UIManager.
