### ISSUE TITLE
Question: Can we save into a new file?

### ISSUE THREAD

**Issue by JimTeva** [hhunaid/react-native-image-crop-tools#9]
Hi @hhunaid, can we save the new cropped image into a new one instead of rewriting the first?

**Comment by hhunaid** [comment]
It's not rewriting the original image. The image is always saved as a new image with a random file name.

**Comment by JimTeva** [comment]
Thanks!

**Comment by rycks** [comment]
Hello @hhunaid,
i'm sorry but how could i get the "random" filename ? is there a propertie with new file name ?

**Comment by rajscet** [comment]
But how to get that file path?.
